"use client";

import { FormEvent, ReactNode, useEffect, useRef, useState, useTransition } from "react";
import { CalendarDays, ChevronRight, Download, LayoutDashboard, MoreHorizontal, Pencil, Plus, Trash2, Users, X } from "lucide-react";
import { toast } from "sonner";
import { AdminMetrics } from "@/components/dashboard/admin-metrics";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { currency, dateBR, timeRange } from "@/lib/utils";
import type { AppointmentStatus } from "@/types/database";

type Action = (formData: FormData) => Promise<void | { ok?: boolean; message?: string }>;
type Service = { id: string; nome: string; descricao: string | null; valor: number; duracao_minutos: number; ativo: boolean };
type Professional = { id: string; nome: string; especialidade: string | null; telefone: string | null; foto_url: string | null; ativo: boolean };
type Availability = { id: string; profissional_id: string; dia_semana: number; hora_inicio: string; hora_fim: string; profissionalNome: string };
type Relation = { profissional_id: string; servico_id: string; profissionalNome: string; servicoNome: string };
type Appointment = { id: string; cliente_nome: string | null; data: string; hora_inicio: string; hora_fim: string; status: AppointmentStatus; servicoNome: string | null; profissionalNome: string | null; valor: number };

const desktopSections = [["overview", "Visão geral"], ["agenda", "Agenda"], ["services", "Serviços"], ["professionals", "Profissionais"], ["availability", "Disponibilidade"], ["reports", "Relatórios"]] as const;
const mobileTabs = [["overview", "Visão geral"], ["agenda", "Agenda"], ["management", "Gestão"]] as const;
type Section = (typeof desktopSections)[number][0] | "management";
const weekdays = ["Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"];

function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) {
  return <div className="py-2 text-center"><p className="font-medium">{title}</p><p className="mt-0.5 text-sm text-muted-foreground">{description}</p>{action && <div className="mt-3">{action}</div>}</div>;
}

function SectionHeader({ title, description, action, compact = false }: { title: string; description?: string; action?: ReactNode; compact?: boolean }) {
  return <div className={compact ? "mb-3 flex items-center justify-between gap-3" : "mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"}><div><h2 className="text-lg font-semibold tracking-tight sm:text-xl">{title}</h2>{description && <p className="mt-0.5 text-sm text-muted-foreground">{description}</p>}</div>{action}</div>;
}

function ActionForm({ action, children, successMessage, onSuccess, className }: { action: Action; children: ReactNode; successMessage: string; onSuccess?: () => void; className?: string }) {
  const [pending, startTransition] = useTransition();
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); startTransition(async () => { try { const result = await action(data); if (result?.ok === false) { toast.error(result.message ?? "Não foi possível concluir a ação."); return; } toast.success(result?.message ?? successMessage); onSuccess?.(); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível concluir a ação."); } }); }
  return <form className={className} onSubmit={submit}>{children}<Button className="w-full sm:w-auto" type="submit" disabled={pending}>{pending ? "Salvando..." : "Salvar"}</Button></form>;
}

function FormDialog({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) dialog.showModal(); if (!open && dialog.open) dialog.close(); }, [open]);
  return <dialog ref={ref} onClose={onClose} aria-labelledby="admin-dialog-title" className="m-auto w-[calc(100%-1.5rem)] max-w-xl rounded-xl border bg-background p-0 text-foreground shadow-2xl backdrop:bg-black/45"><div className="max-h-[calc(100dvh-1.5rem)] overflow-y-auto p-5 sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><h2 id="admin-dialog-title" className="text-xl font-semibold">{title}</h2><Button type="button" variant="ghost" className="size-11 shrink-0 px-0" aria-label="Fechar" onClick={onClose}><X size={20}/></Button></div>{children}</div></dialog>;
}

function MobileBottomNav({ section, navigate }: { section: Section; navigate: (section: Section) => void }) {
  const items = [["overview", "Início", LayoutDashboard], ["agenda", "Agenda", CalendarDays], ["management", "Gestão", Users], ["reports", "Mais", MoreHorizontal]] as const;
  return <nav aria-label="Navegação administrativa" className="fixed inset-x-0 bottom-0 z-20 border-t bg-background/95 px-2 pb-[max(0.5rem,env(safe-area-inset-bottom))] pt-1.5 backdrop-blur md:hidden"><div className="mx-auto grid max-w-md grid-cols-4">{items.map(([id, label, Icon]) => { const active = section === id || (id === "management" && ["services", "professionals", "availability"].includes(section)); return <button key={id} type="button" aria-current={active ? "page" : undefined} onClick={() => navigate(id)} className={"flex min-h-12 flex-col items-center justify-center gap-0.5 rounded-md text-[11px] font-medium transition " + (active ? "text-primary" : "text-muted-foreground hover:bg-muted")}><Icon size={19}/><span>{label}</span></button>; })}</div></nav>;
}

export function AdminWorkspace({ establishmentName, appointments, services, professionals, availability, relations, users, createService, updateService, deleteService, createProfessional, updateProfessional, deleteProfessional, createAvailability, updateAvailability, deleteAvailability, createRelation, deleteRelation }: { establishmentName: string; appointments: Appointment[]; services: Service[]; professionals: Professional[]; availability: Availability[]; relations: Relation[]; users: number; createService: Action; updateService: Action; deleteService: Action; createProfessional: Action; updateProfessional: Action; deleteProfessional: Action; createAvailability: Action; updateAvailability: Action; deleteAvailability: Action; createRelation: Action; deleteRelation: Action }) {
  const actions = { createService, updateService, deleteService, createProfessional, updateProfessional, deleteProfessional, createAvailability, updateAvailability, deleteAvailability, createRelation, deleteRelation };
  const [section, setSection] = useState<Section>("overview");
  const [dialog, setDialog] = useState<"service" | "professional" | "availability" | null>(null);
  const [editing, setEditing] = useState<Service | Professional | Availability | null>(null);
  const activeServices = services.filter((item) => item.ativo), activeProfessionals = professionals.filter((item) => item.ativo);
  const confirmed = appointments.filter((item) => item.status !== "cancelado"), revenue = confirmed.reduce((sum, item) => sum + Number(item.valor || 0), 0);
  const serviceRanking = services.map((service) => ({ ...service, total: appointments.filter((appointment) => appointment.servicoNome === service.nome).length })).sort((a, b) => b.total - a.total);
  const managementActions = [["services", "Serviço", Plus], ["professionals", "Profissional", Users], ["availability", "Horário", CalendarDays]] as const;
  const close = () => { setDialog(null); setEditing(null); };
  const openCreate = (kind: "service" | "professional" | "availability") => { setEditing(null); setDialog(kind); };
  const navigate = (next: Section) => { setSection(next); document.getElementById("admin-content")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const serviceLinks = (id: string) => relations.filter((link) => link.profissional_id === id).map((link) => link.servicoNome);

  return <div className="mx-auto max-w-7xl px-4 py-4 pb-24 sm:px-6 sm:py-6 sm:pb-8 lg:py-8">
    <header className="mb-3 flex items-start justify-between gap-3 sm:mb-6"><div className="min-w-0"><p className="truncate text-sm font-semibold text-primary">{establishmentName}</p><h1 className="mt-0.5 text-2xl font-bold tracking-tight sm:mt-1 sm:text-3xl">Painel administrativo</h1><p className="mt-2 hidden max-w-2xl text-sm text-muted-foreground sm:block">Acompanhe a operação e acesse as áreas de gestão sem sobrecarregar a tela.</p></div><Button variant="secondary" type="button" className="hidden shrink-0 sm:inline-flex"><Download size={16}/> Exportar</Button></header>
    <div className="mb-4 md:hidden"><nav aria-label="Seções principais" className="grid grid-cols-3 rounded-lg bg-muted p-1">{mobileTabs.map(([id, label]) => { const active = section === id || (id === "management" && ["services", "professionals", "availability"].includes(section)); return <button key={id} type="button" onClick={() => navigate(id)} aria-current={active ? "page" : undefined} className={"min-h-11 rounded-md px-2 text-sm font-semibold transition " + (active ? "bg-background text-foreground shadow-sm" : "text-muted-foreground")}>{label}</button>; })}</nav></div>
    <div className="lg:grid lg:grid-cols-[12rem_minmax(0,1fr)] lg:gap-8"><aside className="hidden lg:block"><nav aria-label="Áreas administrativas" className="sticky top-20 flex flex-col gap-1">{desktopSections.map(([id, label]) => <button key={id} type="button" onClick={() => navigate(id)} aria-current={section === id ? "page" : undefined} className={"h-11 rounded-md px-3 text-left text-sm font-medium transition " + (section === id ? "bg-primary text-primary-foreground" : "hover:bg-muted")}>{label}</button>)}</nav></aside>
      <div id="admin-content" className="min-w-0">
        {section === "overview" && <><AdminMetrics appointments={appointments.length} revenue={revenue} services={activeServices.length} professionals={activeProfessionals.length}/><div className="mt-5 grid gap-6 xl:grid-cols-[minmax(0,1.3fr)_minmax(18rem,.7fr)]"><section><SectionHeader title="Próximos agendamentos" action={<button className="min-h-11 text-sm font-semibold text-primary" onClick={() => navigate("agenda")}>Ver agenda</button>} compact/><AppointmentList appointments={appointments.slice(0, 3)} onAgenda={() => navigate("agenda")}/></section><div className="space-y-6"><section><SectionHeader title="Ações rápidas" compact/><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-1">{managementActions.map(([id,label,Icon]) => <button key={id} onClick={() => openCreate(id === "services" ? "service" : id === "professionals" ? "professional" : "availability")} className="flex min-h-11 items-center gap-2 rounded-md border px-3 text-left text-sm font-semibold transition hover:bg-muted"><Icon size={16} className="text-primary"/><span className="truncate">+ {label}</span></button>)}</div></section><section><SectionHeader title="Serviços mais utilizados" compact/>{serviceRanking.some((item) => item.total > 0) ? <div className="divide-y">{serviceRanking.filter((item) => item.total > 0).slice(0,3).map((item) => <div key={item.id} className="flex min-h-11 items-center justify-between gap-3"><span className="truncate font-medium">{item.nome}</span><span className="shrink-0 text-sm text-muted-foreground">{item.total} agend.</span></div>)}</div> : <EmptyState title="Ainda não há dados" description="Os serviços mais utilizados aparecerão aqui."/>}</section></div></div></>}
        {section === "management" && <section><SectionHeader title="Gestão" description="Cadastros e horários do estabelecimento."/><div className="grid gap-2 sm:grid-cols-3">{managementActions.map(([id,label,Icon]) => <button key={id} onClick={() => navigate(id)} className="flex min-h-12 items-center justify-between rounded-md border px-3 text-left font-semibold transition hover:bg-muted"><span className="flex items-center gap-2"><Icon size={17} className="text-primary"/>{label}s</span><ChevronRight size={17} className="text-muted-foreground"/></button>)}</div></section>}
        {section === "agenda" && <section><SectionHeader title="Agenda" description="Agendamentos do estabelecimento, com status e horário."/><AppointmentList appointments={appointments} full onAgenda={() => navigate("agenda")}/></section>}
        {section === "services" && <EntityList title="Serviços" description={`${services.length} cadastrados`} createLabel="Novo serviço" onCreate={() => openCreate("service")} emptyTitle="Nenhum serviço cadastrado" emptyDescription="Cadastre seu primeiro serviço para começar.">{services.map((item) => <div key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="font-semibold">{item.nome}</p><p className="mt-1 text-sm text-muted-foreground">{item.descricao || "Sem descrição"} · {currency(item.valor)} · {item.duracao_minutos} min</p></div><div className="flex items-center gap-2"><Status active={item.ativo}/><Button variant="secondary" onClick={() => { setEditing(item); setDialog("service"); }}><Pencil size={16}/> Editar</Button><DeleteButton action={actions.deleteService} id={item.id} label="serviço"/></div></div>)}</EntityList>}
        {section === "professionals" && <EntityList title="Profissionais" description="Gerencie dados e serviços atendidos." createLabel="Novo profissional" onCreate={() => openCreate("professional")} emptyTitle="Nenhum profissional cadastrado" emptyDescription="Cadastre um profissional para organizar a agenda.">{professionals.map((item) => <div key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3">{item.foto_url ? <img src={item.foto_url} alt="" className="size-11 rounded-full object-cover"/> : <span className="grid size-11 shrink-0 place-items-center rounded-full bg-primary/15 font-semibold text-primary">{item.nome.slice(0,1)}</span>}<div className="min-w-0"><p className="font-semibold">{item.nome}</p><p className="truncate text-sm text-muted-foreground">{item.especialidade || "Sem especialidade"}{item.telefone ? ` · ${item.telefone}` : ""}</p><p className="mt-1 text-xs text-muted-foreground">{serviceLinks(item.id).join(", ") || "Nenhum serviço vinculado"}</p></div></div><div className="flex items-center gap-2"><Status active={item.ativo}/><Button variant="secondary" onClick={() => { setEditing(item); setDialog("professional"); }}><Pencil size={16}/> Editar</Button><DeleteButton action={actions.deleteProfessional} id={item.id} label="profissional"/></div></div>)}</EntityList>}
        {section === "availability" && <EntityList title="Disponibilidade" description="Horários de atendimento por profissional." createLabel="Nova disponibilidade" onCreate={() => openCreate("availability")} emptyTitle="Nenhuma disponibilidade cadastrada" emptyDescription="Adicione horários para liberar a agenda.">{availability.map((item) => <div key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.profissionalNome}</p><p className="text-sm text-muted-foreground">{weekdays[item.dia_semana]} · {timeRange(item.hora_inicio, item.hora_fim)}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={() => { setEditing(item); setDialog("availability"); }}><Pencil size={16}/> Editar</Button><DeleteButton action={actions.deleteAvailability} id={item.id} label="disponibilidade"/></div></div>)}</EntityList>}
        {section === "reports" && <div><SectionHeader title="Mais" action={<Button variant="secondary" type="button"><Download size={16}/> Exportar</Button>}/><div className="grid gap-6 lg:grid-cols-2"><section><SectionHeader title="Resumo operacional"/><dl className="divide-y text-sm"><MetricRow label="Administradores" value={users}/><MetricRow label="Agendamentos confirmados" value={confirmed.length}/><MetricRow label="Faturamento estimado" value={currency(revenue)}/></dl></section><section><SectionHeader title="Atividade por serviço"/>{serviceRanking.some((item) => item.total > 0) ? <div className="divide-y">{serviceRanking.filter((item) => item.total > 0).map((item) => <div key={item.id} className="flex min-h-11 justify-between gap-3 text-sm"><span className="truncate">{item.nome}</span><span className="shrink-0 font-semibold">{item.total} agend.</span></div>)}</div> : <EmptyState title="Sem agendamentos" description="Os indicadores aparecerão conforme a agenda for utilizada."/>}</section></div></div>}
      </div></div>
    <MobileBottomNav section={section} navigate={navigate}/>
    <FormDialog open={dialog === "service"} onClose={close} title={editing && "valor" in editing ? "Editar serviço" : "Novo serviço"}><ActionForm action={editing && "valor" in editing ? actions.updateService : actions.createService} successMessage="Serviço salvo com sucesso." onSuccess={close} className="grid gap-4"><input type="hidden" name="id" value={editing?.id ?? ""}/><Field label="Nome"><Input name="nome" defaultValue={editing && "valor" in editing ? editing.nome : ""} required autoFocus/></Field><Field label="Descrição"><Input name="descricao" defaultValue={editing && "valor" in editing ? editing.descricao ?? "" : ""}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Valor"><Input name="valor" type="number" min="0" step="0.01" defaultValue={editing && "valor" in editing ? editing.valor : ""} required/></Field><Field label="Duração (minutos)"><Input name="duracao_minutos" type="number" min="1" defaultValue={editing && "valor" in editing ? editing.duracao_minutos : 30} required/></Field></div>{editing && "valor" in editing && <Field label="Status"><Select name="ativo" defaultValue={String(editing.ativo)}><option value="true">Ativo</option><option value="false">Inativo</option></Select></Field>}</ActionForm></FormDialog>
    <FormDialog open={dialog === "professional"} onClose={close} title={editing && "especialidade" in editing ? "Editar profissional" : "Novo profissional"}><ActionForm action={editing && "especialidade" in editing ? actions.updateProfessional : actions.createProfessional} successMessage="Profissional salvo com sucesso." onSuccess={close} className="grid gap-4"><input type="hidden" name="id" value={editing?.id ?? ""}/><Field label="Nome"><Input name="nome" defaultValue={editing && "especialidade" in editing ? editing.nome : ""} required autoFocus/></Field><Field label="Especialidade"><Input name="especialidade" defaultValue={editing && "especialidade" in editing ? editing.especialidade ?? "" : ""}/></Field><Field label="WhatsApp"><Input name="telefone" type="tel" defaultValue={editing && "especialidade" in editing ? editing.telefone ?? "" : ""}/></Field><Field label="URL da foto"><Input name="foto_url" type="url" defaultValue={editing && "especialidade" in editing ? editing.foto_url ?? "" : ""}/></Field>{editing && "especialidade" in editing && <><Field label="Status"><Select name="ativo" defaultValue={String(editing.ativo)}><option value="true">Ativo</option><option value="false">Inativo</option></Select></Field><RelationManager professional={editing} services={services} linked={relations.filter((link) => link.profissional_id === editing.id)} create={actions.createRelation} remove={actions.deleteRelation}/></>}</ActionForm></FormDialog>
    <FormDialog open={dialog === "availability"} onClose={close} title={editing && "dia_semana" in editing ? "Editar disponibilidade" : "Nova disponibilidade"}><ActionForm action={editing && "dia_semana" in editing ? actions.updateAvailability : actions.createAvailability} successMessage="Disponibilidade salva com sucesso." onSuccess={close} className="grid gap-4"><input type="hidden" name="id" value={editing?.id ?? ""}/><Field label="Profissional"><Select name="profissional_id" defaultValue={editing && "dia_semana" in editing ? editing.profissional_id : ""} required><option value="" disabled>Selecione</option>{activeProfessionals.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</Select></Field><Field label="Dia da semana"><Select name="dia_semana" defaultValue={editing && "dia_semana" in editing ? String(editing.dia_semana) : ""} required><option value="" disabled>Selecione</option>{weekdays.map((day,index) => <option key={day} value={index}>{day}</option>)}</Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Início"><Input name="hora_inicio" type="time" defaultValue={editing && "dia_semana" in editing ? editing.hora_inicio : ""} required/></Field><Field label="Fim"><Input name="hora_fim" type="time" defaultValue={editing && "dia_semana" in editing ? editing.hora_fim : ""} required/></Field></div></ActionForm></FormDialog>
  </div>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium"><span>{label}</span>{children}</label>; }
function Status({ active }: { active: boolean }) { return <span className={"rounded-full px-2 py-1 text-xs font-medium " + (active ? "bg-primary/15 text-primary" : "bg-muted text-muted-foreground")}>{active ? "Ativo" : "Inativo"}</span>; }
function MetricRow({ label, value }: { label: string; value: ReactNode }) { return <div className="flex min-h-11 items-center justify-between gap-3"><dt>{label}</dt><dd className="font-semibold">{value}</dd></div>; }
function EntityList({ title, description, createLabel, onCreate, emptyTitle, emptyDescription, children }: { title: string; description: string; createLabel: string; onCreate: () => void; emptyTitle: string; emptyDescription: string; children: ReactNode[] }) { return <section><SectionHeader title={title} description={description} action={<Button onClick={onCreate}><Plus size={16}/>{createLabel}</Button>}/>{children.length ? <div className="divide-y">{children}</div> : <EmptyState title={emptyTitle} description={emptyDescription} action={<Button onClick={onCreate}><Plus size={16}/>{createLabel}</Button>}/>}</section>; }
function DeleteButton({ action, id, label }: { action: Action; id: string; label: string }) { const [pending, startTransition] = useTransition(); return <Button variant="ghost" type="button" disabled={pending} aria-label={`Excluir ${label}`} onClick={() => { if (!window.confirm(`Deseja realmente excluir este ${label}?`)) return; startTransition(async () => { const data = new FormData(); data.set("id", id); const result = await action(data); result?.ok === false ? toast.error(result.message ?? "Não foi possível excluir.") : toast.success(result?.message ?? "Excluído com sucesso."); }); }}><Trash2 size={16}/><span className="sr-only sm:not-sr-only">Excluir</span></Button>; }
function AppointmentList({ appointments, full = false, onAgenda }: { appointments: Appointment[]; full?: boolean; onAgenda: () => void }) { if (!appointments.length) return <EmptyState title={full ? "Nenhum agendamento registrado" : "Nenhum agendamento para hoje"} description="Os próximos horários aparecerão aqui." action={!full ? <button onClick={onAgenda} className="min-h-11 text-sm font-semibold text-primary">Ver agenda</button> : undefined}/>; return <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="py-3 font-medium">Cliente</th><th className="py-3 font-medium">Serviço</th><th className="py-3 font-medium">Profissional</th><th className="py-3 font-medium">Data</th><th className="py-3 font-medium">Horário</th><th className="py-3 font-medium">Status</th></tr></thead><tbody>{appointments.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="py-3">{item.cliente_nome || "Visitante"}</td><td className="py-3">{item.servicoNome}</td><td className="py-3">{item.profissionalNome}</td><td className="py-3">{dateBR(item.data)}</td><td className="py-3">{timeRange(item.hora_inicio,item.hora_fim)}</td><td className="py-3"><StatusBadge status={item.status}/></td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{appointments.map((item) => <article key={item.id} className="py-2.5 first:pt-0 last:pb-0"><div className="flex items-center justify-between gap-2"><p className="min-w-0 truncate font-semibold"><time>{item.hora_inicio.slice(0,5)}</time><span className="font-normal text-muted-foreground"> · {item.cliente_nome || "Visitante"}</span></p><span className="shrink-0"><StatusBadge status={item.status}/></span></div><p className="mt-0.5 truncate text-sm">{item.servicoNome || "Serviço"} <span className="text-muted-foreground">· {item.profissionalNome || "Sem profissional"}</span></p>{full && <p className="mt-0.5 text-xs text-muted-foreground">{dateBR(item.data)}</p>}</article>)}</div></>; }
function RelationManager({ professional, services, linked, create, remove }: { professional: Professional; services: Service[]; linked: Relation[]; create: Action; remove: Action }) { const linkedIds = new Set(linked.map((item) => item.servico_id)); return <fieldset className="rounded-lg border p-3"><legend className="px-1 text-sm font-semibold">Serviços atendidos</legend><div className="space-y-2">{services.filter((item) => item.ativo).map((service) => <label key={service.id} className="flex min-h-11 items-center justify-between gap-2 text-sm"><span>{service.nome}</span><input type="checkbox" checked={linkedIds.has(service.id)} onChange={async (event) => { const data = new FormData(); data.set("profissional_id", professional.id); data.set("servico_id", service.id); const result = await (event.target.checked ? create : remove)(data); if (result?.ok === false) toast.error(result.message ?? "Não foi possível atualizar o vínculo."); else toast.success("Vínculo atualizado."); }} /></label>)}</div></fieldset>; }
