"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, MessageCircle, Search, SlidersHorizontal, X } from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { buildReactivationMessage, buildWhatsAppUrl, type InactiveCustomer } from "@/lib/reports";
import { currency, dateBR } from "@/lib/utils";

export type ReportSummary = { appointments: number; completed: number; cancelled: number; revenue: number; averageTicket: number; customers: number; newCustomers: number; recurringCustomers: number; cancellationRate: number; topProfessional: string | null; topService: string | null };
export type ServiceReport = { name: string; appointments: number; revenue: number };
export type ProfessionalReport = { name: string; appointments: number; revenue: number; cancelled: number };
type Period = "today" | "7d" | "30d" | "month" | "previous-month";
type Order = "oldest" | "recent" | "name";
const periods: Array<[Period, string]> = [["today", "Hoje"], ["7d", "7 dias"], ["30d", "30 dias"], ["month", "Este mês"], ["previous-month", "Mês anterior"]];

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="min-w-0 rounded-lg border bg-background/80 px-3 py-2.5 shadow-sm sm:p-4"><dt className="truncate text-[11px] font-medium text-muted-foreground sm:text-sm">{label}</dt><dd className="mt-0.5 truncate text-base font-bold tracking-tight sm:mt-1 sm:text-2xl">{value}</dd></div>; }

function FilterSheet({ open, onClose, order, minimumDays, onApply }: { open: boolean; onClose: () => void; order: Order; minimumDays: number; onApply: (order: Order, minimumDays: number) => void }) {
  const ref = useRef<HTMLDialogElement>(null); const [draftOrder, setDraftOrder] = useState<Order>(order), [draftDays, setDraftDays] = useState(minimumDays);
  useEffect(() => { if (open) { setDraftOrder(order); setDraftDays(minimumDays); } }, [minimumDays, open, order]);
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) dialog.showModal(); if (!open && dialog.open) dialog.close(); }, [open]);
  return <dialog ref={ref} onClose={onClose} aria-labelledby="report-filters-title" className="m-0 mt-auto w-full max-w-xl rounded-t-2xl border bg-background p-0 text-foreground shadow-2xl backdrop:bg-black/45 md:m-auto md:rounded-xl"><div className="max-h-[min(32rem,calc(100dvh-1rem))] overflow-y-auto p-4 pb-[max(1rem,env(safe-area-inset-bottom))] sm:p-5"><div className="mb-4 flex items-center justify-between"><h2 id="report-filters-title" className="text-lg font-semibold">Filtros</h2><Button type="button" variant="ghost" className="size-11 px-0" aria-label="Fechar filtros" onClick={onClose}><X size={20}/></Button></div><div className="grid gap-4"><label className="grid gap-1.5 text-sm font-medium">Ordenar por<Select value={draftOrder} onChange={(event) => setDraftOrder(event.target.value as Order)}><option value="oldest">Mais tempo sem retornar</option><option value="recent">Menos tempo sem retornar</option><option value="name">Nome</option></Select></label><label className="grid gap-1.5 text-sm font-medium">Dias sem retorno<Select value={draftDays} onChange={(event) => setDraftDays(Number(event.target.value))}><option value="20">20+ dias</option><option value="30">30+ dias</option><option value="45">45+ dias</option></Select></label></div><div className="mt-5 grid grid-cols-2 gap-2"><Button type="button" variant="secondary" onClick={() => { setDraftOrder("oldest"); setDraftDays(20); }}>Limpar filtros</Button><Button type="button" onClick={() => { onApply(draftOrder, draftDays); onClose(); }}>Aplicar</Button></div></div></dialog>;
}

export function ReportsPage({ tenantSlug, establishmentName, summary, inactiveCustomers, services, professionals }: { tenantSlug: string; establishmentName: string; summary: ReportSummary; inactiveCustomers: InactiveCustomer[]; services: ServiceReport[]; professionals: ProfessionalReport[] }) {
  const router = useRouter(), searchParams = useSearchParams(); const period = (searchParams.get("period") as Period | null) ?? "30d";
  const [query, setQuery] = useState(""), [order, setOrder] = useState<Order>("oldest"), [minimumDays, setMinimumDays] = useState(20), [filtersOpen, setFiltersOpen] = useState(false), [showAll, setShowAll] = useState(false);
  const customers = useMemo(() => inactiveCustomers.filter((customer) => customer.inactiveDays >= minimumDays && `${customer.name} ${customer.phone ?? ""}`.toLocaleLowerCase("pt-BR").includes(query.trim().toLocaleLowerCase("pt-BR"))).toSorted((a, b) => order === "name" ? a.name.localeCompare(b.name, "pt-BR") : order === "recent" ? a.inactiveDays - b.inactiveDays : b.inactiveDays - a.inactiveDays), [inactiveCustomers, minimumDays, order, query]);
  const visibleCustomers = showAll ? customers : customers.slice(0, 5); const selectPeriod = (event: ChangeEvent<HTMLSelectElement>) => router.replace(`/${tenantSlug}/admin/relatorios?period=${event.target.value}`);
  const openWhatsApp = (customer: InactiveCustomer) => { const url = buildWhatsAppUrl(customer.phone, buildReactivationMessage(customer, establishmentName)); if (!url) { toast.error("Este cliente não possui um WhatsApp válido."); return; } window.open(url, "_blank", "noopener,noreferrer"); };
  const highestServiceCount = services[0]?.appointments ?? 0;
  return <main className="mx-auto max-w-7xl px-4 py-3 pb-7 sm:px-6 sm:py-6 lg:py-8"><header className="mb-4 sm:mb-6"><Link href={`/${tenantSlug}/admin`} className="mb-1 inline-flex min-h-9 items-center gap-1 text-sm font-semibold text-primary"><ArrowLeft size={16}/> Painel administrativo</Link><div className="flex items-center justify-between gap-3"><div className="min-w-0"><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Relatórios</h1><p className="mt-1 hidden max-w-2xl text-sm text-muted-foreground sm:block">Acompanhe o desempenho da operação e identifique oportunidades de retorno.</p></div><div className="w-32 shrink-0 sm:w-44"><Select aria-label="Período dos relatórios" value={periods.some(([value]) => value === period) ? period : "30d"} onChange={selectPeriod}>{periods.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></div></div></header>
    <section aria-label="Indicadores principais"><dl className="grid grid-cols-2 gap-2 sm:gap-3 lg:grid-cols-4"><Metric label="Agendamentos" value={summary.appointments}/><Metric label="Faturamento estimado" value={currency(summary.revenue)}/><Metric label="Ticket médio" value={currency(summary.averageTicket)}/><Metric label="Cancelamentos" value={`${summary.cancellationRate}%`}/></dl></section>
    <section className="mt-5 sm:mt-6"><div className="mb-3 flex items-end justify-between gap-3"><div className="min-w-0"><h2 className="text-lg font-semibold">Clientes para reativar <span className="text-primary">{inactiveCustomers.length}</span></h2><p className="mt-0.5 text-sm text-muted-foreground">20+ dias sem atendimento concluído</p></div></div><div className="mb-3 flex gap-2"><label className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-3 text-muted-foreground" size={17}/><Input value={query} onChange={(event) => { setQuery(event.target.value); setShowAll(false); }} className="pl-9" placeholder="Buscar cliente..." aria-label="Buscar cliente inativo"/></label><Button type="button" variant="secondary" className="shrink-0 md:hidden" aria-expanded={filtersOpen} onClick={() => setFiltersOpen(true)}><SlidersHorizontal size={16}/> Filtros</Button><div className="hidden gap-2 md:flex"><Select aria-label="Ordenar clientes" value={order} onChange={(event) => setOrder(event.target.value as Order)} className="w-52"><option value="oldest">Mais tempo sem retornar</option><option value="recent">Menos tempo sem retornar</option><option value="name">Nome</option></Select><Select aria-label="Filtrar dias sem retorno" value={minimumDays} onChange={(event) => setMinimumDays(Number(event.target.value))} className="w-32"><option value="20">20+ dias</option><option value="30">30+ dias</option><option value="45">45+ dias</option></Select></div></div>
      {customers.length ? <><div className="hidden overflow-x-auto rounded-lg border md:block"><table className="w-full text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="p-3 font-medium">Cliente</th><th className="p-3 font-medium">WhatsApp</th><th className="p-3 font-medium">Último atendimento</th><th className="p-3 font-medium">Serviço</th><th className="p-3 font-medium">Sem retornar</th><th className="p-3 font-medium">Ação</th></tr></thead><tbody>{visibleCustomers.map((customer) => <tr className="border-b last:border-0" key={customer.key}><td className="p-3 font-medium">{customer.name}</td><td className="p-3">{customer.phone ?? "Não informado"}</td><td className="p-3">{dateBR(customer.lastAppointmentDate)}</td><td className="p-3">{customer.lastService ?? "—"}</td><td className="p-3 font-semibold">{customer.inactiveDays} dias</td><td className="p-3"><Button onClick={() => openWhatsApp(customer)}><MessageCircle size={16}/> WhatsApp</Button></td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{visibleCustomers.map((customer) => <article key={customer.key} className="py-3 first:pt-0"><div className="flex items-start justify-between gap-3"><p className="min-w-0 truncate font-semibold">{customer.name}</p><span className="shrink-0 text-sm font-bold text-primary">{customer.inactiveDays} dias</span></div><p className="mt-0.5 truncate text-sm text-muted-foreground">{dateBR(customer.lastAppointmentDate)} · {customer.lastService ?? "Serviço não informado"}{customer.lastProfessional ? ` · ${customer.lastProfessional}` : ""}</p><Button className="mt-2 w-full" onClick={() => openWhatsApp(customer)}><MessageCircle size={16}/> WhatsApp</Button></article>)}</div>{customers.length > 5 && <button type="button" className="mt-2 min-h-11 text-sm font-semibold text-primary" onClick={() => setShowAll((value) => !value)}>{showAll ? "Mostrar menos" : `Ver todos os clientes (${customers.length})`}</button>}</> : <div className="border-y py-5 text-sm text-muted-foreground">Nenhum cliente corresponde aos filtros.<br/>Ajuste os filtros ou aguarde novos atendimentos.</div>}</section>
    <section className="mt-6"><h2 className="mb-2 text-base font-semibold">Mais indicadores</h2><dl className="divide-y border-y text-sm"><div className="flex min-h-10 items-center justify-between gap-3"><dt className="text-muted-foreground">Concluídos</dt><dd className="font-semibold">{summary.completed}</dd></div><div className="flex min-h-10 items-center justify-between gap-3"><dt className="text-muted-foreground">Clientes atendidos</dt><dd className="font-semibold">{summary.customers}</dd></div><div className="flex min-h-10 items-center justify-between gap-3"><dt className="text-muted-foreground">Clientes novos</dt><dd className="font-semibold">{summary.newCustomers}</dd></div></dl></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section><h2 className="mb-2 text-base font-semibold">Serviços mais utilizados</h2>{services.length ? <div className="space-y-2.5">{services.map((service) => <div key={service.name}><div className="flex justify-between gap-3 text-sm"><span className="min-w-0 truncate font-medium">{service.name}</span><span className="shrink-0 text-muted-foreground">{service.appointments} atend. · {currency(service.revenue)}</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${highestServiceCount ? service.appointments / highestServiceCount * 100 : 0}%` }}/></div></div>)}</div> : <p className="text-sm text-muted-foreground">Ainda não há atendimentos concluídos no período.</p>}</section><section><h2 className="mb-2 text-base font-semibold">Desempenho por profissional</h2>{professionals.length ? <div className="divide-y border-y">{professionals.map((professional) => <div className="flex min-h-11 items-center justify-between gap-3 py-2" key={professional.name}><span className="min-w-0 truncate font-medium">{professional.name}</span><span className="shrink-0 text-right text-sm text-muted-foreground">{professional.appointments} atend. · {currency(professional.revenue)}</span></div>)}</div> : <p className="text-sm text-muted-foreground">Ainda não há atendimentos concluídos no período.</p>}</section></div>
    <FilterSheet open={filtersOpen} onClose={() => setFiltersOpen(false)} order={order} minimumDays={minimumDays} onApply={(nextOrder, nextMinimumDays) => { setOrder(nextOrder); setMinimumDays(nextMinimumDays); setShowAll(false); }}/>
  </main>;
}
