"use client";

import { ChangeEvent, useMemo, useState } from "react";
import { ArrowLeft, MessageCircle, Search } from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { buildReactivationMessage, buildWhatsAppUrl, type InactiveCustomer } from "@/lib/reports";
import { currency, dateBR } from "@/lib/utils";

export type ReportSummary = { appointments: number; completed: number; cancelled: number; revenue: number; averageTicket: number; customers: number; newCustomers: number; recurringCustomers: number; cancellationRate: number; topProfessional: string | null; topService: string | null };
export type ServiceReport = { name: string; appointments: number; revenue: number };
export type ProfessionalReport = { name: string; appointments: number; revenue: number; cancelled: number };
type Period = "today" | "7d" | "30d" | "month" | "previous-month";
const periods: Array<[Period, string]> = [["today", "Hoje"], ["7d", "7 dias"], ["30d", "30 dias"], ["month", "Este mês"], ["previous-month", "Mês anterior"]];
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border bg-background/80 p-3 shadow-sm sm:p-4"><dt className="text-xs font-medium text-muted-foreground">{label}</dt><dd className="mt-1 truncate text-lg font-bold tracking-tight sm:text-2xl">{value}</dd></div>; }

export function ReportsPage({ tenantSlug, establishmentName, summary, inactiveCustomers, services, professionals }: { tenantSlug: string; establishmentName: string; summary: ReportSummary; inactiveCustomers: InactiveCustomer[]; services: ServiceReport[]; professionals: ProfessionalReport[] }) {
  const router = useRouter(), searchParams = useSearchParams(); const period = (searchParams.get("period") as Period | null) ?? "30d";
  const [query, setQuery] = useState(""), [order, setOrder] = useState("oldest"), [minimumDays, setMinimumDays] = useState(20);
  const customers = useMemo(() => inactiveCustomers.filter((c) => c.inactiveDays >= minimumDays && `${c.name} ${c.phone ?? ""}`.toLocaleLowerCase("pt-BR").includes(query.trim().toLocaleLowerCase("pt-BR"))).toSorted((a,b) => order === "name" ? a.name.localeCompare(b.name, "pt-BR") : order === "recent" ? a.inactiveDays - b.inactiveDays : b.inactiveDays - a.inactiveDays), [inactiveCustomers, minimumDays, order, query]);
  const selectPeriod = (event: ChangeEvent<HTMLSelectElement>) => router.replace(`/${tenantSlug}/admin/relatorios?period=${event.target.value}`);
  const openWhatsApp = (customer: InactiveCustomer) => { const url = buildWhatsAppUrl(customer.phone, buildReactivationMessage(customer, establishmentName)); if (!url) { toast.error("Este cliente não possui um WhatsApp válido."); return; } window.open(url, "_blank", "noopener,noreferrer"); };
  const highestServiceCount = services[0]?.appointments ?? 0;
  return <main className="mx-auto max-w-7xl px-4 py-4 pb-8 sm:px-6 sm:py-6 lg:py-8"><div className="mb-4 flex items-start justify-between gap-3 sm:mb-6"><div className="min-w-0"><Link href={`/${tenantSlug}/admin`} className="mb-2 inline-flex min-h-11 items-center gap-1 text-sm font-semibold text-primary"><ArrowLeft size={16}/> Painel administrativo</Link><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Relatórios</h1><p className="mt-1 hidden max-w-2xl text-sm text-muted-foreground sm:block">Acompanhe o desempenho da operação e identifique oportunidades de retorno.</p></div><div className="w-36 shrink-0 sm:w-44"><Select aria-label="Período dos relatórios" value={periods.some(([value]) => value === period) ? period : "30d"} onChange={selectPeriod}>{periods.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></div></div>
    <section aria-label="Indicadores principais"><dl className="grid grid-cols-2 gap-2.5 lg:grid-cols-4"><Metric label="Agendamentos" value={summary.appointments}/><Metric label="Faturamento estimado" value={currency(summary.revenue)}/><Metric label="Ticket médio" value={currency(summary.averageTicket)}/><Metric label="Cancelamentos" value={`${summary.cancellationRate}%`}/></dl><dl className="mt-2.5 grid grid-cols-3 gap-2.5"><Metric label="Concluídos" value={summary.completed}/><Metric label="Clientes atendidos" value={summary.customers}/><Metric label="Clientes novos" value={summary.newCustomers}/></dl></section>
    <section className="mt-6"><div className="mb-3"><h2 className="text-lg font-semibold">Clientes para reativar</h2><p className="text-sm text-muted-foreground">{inactiveCustomers.length} clientes com 20+ dias sem atendimento concluído.</p></div><div className="mb-3 grid gap-2 sm:grid-cols-[minmax(0,1fr)_11rem_11rem]"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-3 text-muted-foreground" size={17}/><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" placeholder="Buscar nome ou telefone" aria-label="Buscar cliente inativo"/></label><Select aria-label="Ordenar clientes" value={order} onChange={(event) => setOrder(event.target.value)}><option value="oldest">Mais tempo sem retornar</option><option value="recent">Menos tempo sem retornar</option><option value="name">Nome</option></Select><Select aria-label="Filtrar dias sem retorno" value={minimumDays} onChange={(event) => setMinimumDays(Number(event.target.value))}><option value="20">20+ dias</option><option value="30">30+ dias</option><option value="45">45+ dias</option></Select></div>{customers.length ? <><div className="hidden overflow-x-auto rounded-lg border md:block"><table className="w-full text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="p-3 font-medium">Cliente</th><th className="p-3 font-medium">WhatsApp</th><th className="p-3 font-medium">Último atendimento</th><th className="p-3 font-medium">Serviço</th><th className="p-3 font-medium">Sem retornar</th><th className="p-3 font-medium">Ação</th></tr></thead><tbody>{customers.map((c) => <tr className="border-b last:border-0" key={c.key}><td className="p-3 font-medium">{c.name}</td><td className="p-3">{c.phone ?? "Não informado"}</td><td className="p-3">{dateBR(c.lastAppointmentDate)}</td><td className="p-3">{c.lastService ?? "—"}</td><td className="p-3 font-semibold">{c.inactiveDays} dias</td><td className="p-3"><Button onClick={() => openWhatsApp(c)}><MessageCircle size={16}/> WhatsApp</Button></td></tr>)}</tbody></table></div><div className="divide-y rounded-lg border px-3 md:hidden">{customers.map((c) => <article key={c.key} className="py-3"><div className="flex items-start justify-between gap-3"><p className="min-w-0 truncate font-semibold">{c.name}</p><span className="shrink-0 text-sm font-bold text-primary">{c.inactiveDays} dias</span></div><p className="mt-1 truncate text-sm text-muted-foreground">{dateBR(c.lastAppointmentDate)} · {c.lastService ?? "Serviço não informado"}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{c.lastProfessional ? `com ${c.lastProfessional}` : ""}</p><Button className="mt-3 w-full" onClick={() => openWhatsApp(c)}><MessageCircle size={16}/> Enviar WhatsApp</Button></article>)}</div></> : <div className="rounded-lg border py-8 text-center text-sm text-muted-foreground">Nenhum cliente corresponde aos filtros.</div>}</section>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section><h2 className="mb-3 text-lg font-semibold">Serviços mais utilizados</h2>{services.length ? <div className="space-y-3">{services.map((service) => <div key={service.name}><div className="flex justify-between gap-3 text-sm"><span className="truncate font-medium">{service.name}</span><span className="shrink-0">{service.appointments} atend. · {currency(service.revenue)}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${highestServiceCount ? service.appointments / highestServiceCount * 100 : 0}%` }}/></div></div>)}</div> : <p className="text-sm text-muted-foreground">Ainda não há atendimentos concluídos no período.</p>}</section><section><h2 className="mb-3 text-lg font-semibold">Desempenho por profissional</h2>{professionals.length ? <div className="divide-y rounded-lg border">{professionals.map((p) => <div className="flex min-h-12 items-center justify-between gap-3 px-3 py-2" key={p.name}><span className="truncate font-medium">{p.name}</span><span className="shrink-0 text-right text-sm text-muted-foreground">{p.appointments} atend. · {currency(p.revenue)}</span></div>)}</div> : <p className="text-sm text-muted-foreground">Ainda não há atendimentos concluídos no período.</p>}</section></div>
  </main>;
}
