import type { InactiveCustomer } from "@/lib/reports";

type Appointment = { id: string; cliente_id: string | null; cliente_nome: string | null; cliente_telefone: string | null; data: string; hora_fim: string; status: string; servicos: { nome: string; valor: number } | { nome: string; valor: number }[] | null; profissionais: { nome: string } | { nome: string }[] | null };
const pick = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] ?? null : value;
const todayFortaleza = () => { const parts = new Intl.DateTimeFormat("en", { timeZone: "America/Fortaleza", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const part = (type: string) => parts.find((item) => item.type === type)?.value ?? "01"; return `${part("year")}-${part("month")}-${part("day")}`; };
const keyFor = (appointment: Appointment) => appointment.cliente_id ? `id:${appointment.cliente_id}` : `phone:${(appointment.cliente_telefone ?? "").replace(/\D/g, "")}`;
const contactable = (phone: string | null) => /^(55)?[1-9]\d9?\d{8}$/.test((phone ?? "").replace(/\D/g, ""));

export function buildReportFallback(appointments: Appointment[], startDate: string, endDate: string) {
  const today = todayFortaleza(); const inPeriod = appointments.filter((item) => item.data >= startDate && item.data <= endDate); const completed = inPeriod.filter((item) => item.status === "finalizado"); const history = appointments.filter((item) => item.status === "finalizado" && item.data <= today && item.cliente_telefone);
  const revenue = completed.reduce((total, item) => total + Number(pick(item.servicos)?.valor ?? 0), 0); const customerKeys = new Set(completed.filter((item) => item.cliente_telefone).map(keyFor));
  const lastByCustomer = new Map<string, Appointment>(); for (const item of history.sort((a, b) => `${b.data}${b.hora_fim}${b.id}`.localeCompare(`${a.data}${a.hora_fim}${a.id}`))) { if (!lastByCustomer.has(keyFor(item))) lastByCustomer.set(keyFor(item), item); }
  const inactiveCustomers: InactiveCustomer[] = [...lastByCustomer.values()].filter((item) => contactable(item.cliente_telefone)).map((item) => { const service = pick(item.servicos), professional = pick(item.profissionais); const inactiveDays = Math.floor((Date.parse(`${today}T00:00:00Z`) - Date.parse(`${item.data}T00:00:00Z`)) / 86_400_000); return { key: keyFor(item), name: item.cliente_nome?.trim() || "Cliente", phone: item.cliente_telefone, lastAppointmentDate: item.data, lastService: service?.nome ?? null, lastProfessional: professional?.nome ?? null, inactiveDays }; }).filter((item) => item.inactiveDays >= 20).sort((a, b) => b.inactiveDays - a.inactiveDays || a.name.localeCompare(b.name, "pt-BR"));
  const grouped = <T extends { name: string }>(items: Appointment[], name: (item: Appointment) => string | null, cancelled = false) => Object.values(items.reduce<Record<string, T & { appointments: number; revenue: number; cancelled?: number }>>((result, item) => { const itemName = name(item); if (!itemName) return result; const current = result[itemName] ?? { name: itemName, appointments: 0, revenue: 0, ...(cancelled ? { cancelled: 0 } : {}) } as T & { appointments: number; revenue: number; cancelled?: number }; if (item.status === "finalizado") { current.appointments += 1; current.revenue += Number(pick(item.servicos)?.valor ?? 0); } if (cancelled && item.status === "cancelado") current.cancelled = (current.cancelled ?? 0) + 1; result[itemName] = current; return result; }, {})).sort((a, b) => b.appointments - a.appointments || a.name.localeCompare(b.name, "pt-BR"));
  const services = grouped<{ name: string }>(completed, (item) => pick(item.servicos)?.nome ?? null); const professionals = grouped<{ name: string }>(inPeriod, (item) => pick(item.profissionais)?.nome ?? null, true);
  const priorCustomerKeys = new Set(history.filter((item) => item.data < startDate).map(keyFor)); const cancelled = inPeriod.filter((item) => item.status === "cancelado").length;
  return { summary: { appointments: inPeriod.length, completed: completed.length, cancelled, revenue, averageTicket: completed.length ? revenue / completed.length : 0, customers: customerKeys.size, newCustomers: [...customerKeys].filter((key) => !priorCustomerKeys.has(key)).length, recurringCustomers: [...customerKeys].filter((key) => priorCustomerKeys.has(key)).length, cancellationRate: inPeriod.length ? Math.round(cancelled / inPeriod.length * 1000) / 10 : 0, topProfessional: professionals[0]?.name ?? null, topService: services[0]?.name ?? null }, inactive_customers: inactiveCustomers, services, professionals };
}
