import { notFound, redirect } from "next/navigation";
import { Navbar } from "@/components/navbar";
import { ReportsPage, type ProfessionalReport, type ReportSummary, type ServiceReport } from "@/components/dashboard/reports-page";
import { hasSupabaseEnv } from "@/lib/config";
import { getEstablishmentBySlug } from "@/lib/establishments";
import { requireTenantAdministrator } from "@/lib/tenant-access";
import type { InactiveCustomer } from "@/lib/reports";
import { buildReportFallback } from "@/lib/reports-server";
export const dynamic = "force-dynamic";
function periodRange(period?: string) { const parts = new Intl.DateTimeFormat("en", { timeZone: "America/Fortaleza", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const get = (type: string) => parts.find((part) => part.type === type)?.value ?? "01"; const year = Number(get("year")), month = Number(get("month")), date = Number(get("day")), today = `${get("year")}-${get("month")}-${get("day")}`; const day = new Date(Date.UTC(year, month - 1, date)), format = (value: Date) => value.toISOString().slice(0, 10); if (period === "today") return [today, today]; if (period === "7d") { day.setUTCDate(day.getUTCDate() - 6); return [format(day), today]; } if (period === "month") return [format(new Date(Date.UTC(year, month - 1, 1))), today]; if (period === "previous-month") return [format(new Date(Date.UTC(year, month - 2, 1))), format(new Date(Date.UTC(year, month - 1, 0)))]; day.setUTCDate(day.getUTCDate() - 29); return [format(day), today]; }
export default async function ReportsRoute({ params, searchParams }: { params: Promise<{ tenantSlug: string }>; searchParams: Promise<{ period?: string }> }) { const [{ tenantSlug }, { period }] = await Promise.all([params, searchParams]); const establishment = await getEstablishmentBySlug(tenantSlug); if (!establishment) notFound(); if (!hasSupabaseEnv()) redirect(`/${tenantSlug}/admin/login`); let supabase: any; try { ({ supabase } = await requireTenantAdministrator(tenantSlug)); } catch { redirect(`/${tenantSlug}/admin/login`); } const [startDate, endDate] = periodRange(period); const { data, error } = await supabase.rpc("get_admin_report", { p_estabelecimento_id: establishment.id, p_start_date: startDate, p_end_date: endDate, p_inactive_days: 20 }); let report = data; if (error) { const { data: appointments, error: appointmentsError } = await supabase.from("agendamentos").select("id, cliente_id, cliente_nome, cliente_telefone, data, hora_fim, status, servicos(nome, valor), profissionais(nome)").eq("estabelecimento_id", establishment.id).order("data", { ascending: false }).order("hora_fim", { ascending: false }); if (appointmentsError) throw new Error("Não foi possível carregar os relatórios."); report = buildReportFallback(appointments ?? [], startDate, endDate); } return <><Navbar/><ReportsPage tenantSlug={tenantSlug} establishmentName={establishment.nome} summary={(report?.summary ?? {}) as ReportSummary} inactiveCustomers={(report?.inactive_customers ?? []) as InactiveCustomer[]} services={(report?.services ?? []) as ServiceReport[]} professionals={(report?.professionals ?? []) as ProfessionalReport[]}/></>; }
